#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

PROOT="proot";
PROOT_CMD_LINE="./proot -r ubuntu -b /dev -b /etc/resolv.conf -b /proc" 
PROOT_CMD_LINE_ROOT="$PROOT_CMD_LINE  -0" 

if mkdir mylock; then
rm -rf $PROOT;
wget https://github.com/maxired/proot-static-build/raw/master/static/proot
chmod +x $PROOT
rm -rf ubuntu/*;
mkdir ubuntu;
cd ubuntu;
wget http://download.openvz.org/template/precreated/ubuntu-12.04-x86_64.tar.gz
tar xzf ubuntu-12.04-x86_64.tar.gz
echo "source /etc/environment" >> etc/bash.bashrc
echo "export PATH=/node-v0.8.25-linux-x64/bin/:/sbin:$PATH" >> etc/bash.bashrc
echo "export HOME=/root" >> etc/bash.bashrc

rm -rf ubuntu-12.04-x86_64.tar.gz
cd ..
cd ubuntu
wget http://nodejs.org/dist/v0.8.25/node-v0.8.25-linux-x64.tar.gz
tar xzf node-v0.8.25-linux-x64.tar.gz 
rm -rf node-v0.8.25-linux-x64.tar.gz


rm -rf install.sh
echo "export PATH=/sbin:$PATH" >> install.sh
echo "apt-get -y update" >> install.sh 
echo "apt-get -y install build-essential" >> install.sh 
chmod +x install.sh
cd ..
$PROOT_CMD_LINE_ROOT /install.sh

fi



#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &
